package com.github.hicoincom.crypto.rsa;

import java.io.Serializable;

public class RSAKey implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Private data members, mainly public and private keys are generated by the program itself,
	 * and the public key needs to be passed to the other party of communication
	 */
	public String publicKey;

	public String privateKey;

	public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	public String getPrivateKey() {
		return privateKey;
	}

	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey;
	}
}
